### ISSUE TITLE
Having trouble installing package

### ISSUE THREAD

**Issue by jalalsiddiqui** [FedericoComoglio/wavClusteR#8]
I am trying to install and run this package on the cluster but keep getting errors:

Enter one or more numbers, or an empty line to skip updates: 3
✓  checking for file ‘/tmp/Rtmp8Hmc02/remotes7a79ee1fbf3/FedericoComoglio-wavClusteR-ea74fd5/DESCRIPTION’ ... OK
─  preparing ‘wavClusteR’:
✓  checking DESCRIPTION meta-information ... 
─  installing the package to build vignettes
         -----------------------------------
   ERROR: dependency ‘wmtsa’ is not available for package ‘wavClusteR’
─  removing ‘/tmp/RtmprFHj07/Rinstc3a651dc589d/wavClusteR’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'wavClusteR' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/tmp/Rtmp8Hmc02/remotes7a79ee1fbf3/FedericoComoglio-wavClusteR-ea74fd5/DESCRIPTION’ ... OK
E> * preparing ‘wavClusteR’:
E> * checking DESCRIPTION meta-information ... OK
E> * installing the package to build vignettes
E>       -----------------------------------
E> ERROR: dependency ‘wmtsa’ is not available for package ‘wavClusteR’
E> * removing ‘/tmp/RtmprFHj07/Rinstc3a651dc589d/wavClusteR’
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by FedericoComoglio** [comment]
Hi @jalalsiddiqui, thank you for getting in touch. Could you please share the exact command you executed for installing the package? I suspect you are installing the `devel` version, which still maintains a legacy dependency on `wmtsa`. Could you please try to install from `master` using (or from BioC directly)?

```
install_github(repo = "FedericoComoglio/wavClusteR", build_vignettes = TRUE)
```

Let me know.

**Comment by jalalsiddiqui** [comment]
I used this command:


if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("wavClusteR")

________________________________

**Comment by FedericoComoglio** [comment]
Could you please share your R version and the [output](https://devtools.r-lib.org/reference/session_info.html) of `devtools::session_info`? The `wmtsa` package is no longer a dependency and I suspect you are running R < 4.x. Thank you.

**Comment by jalalsiddiqui** [comment]
I will try on R 3.5.1 but get this error:

> library(wavClusterR)> wavClusteR::wavClusteR::> wavClusteR::wavClusteR::> BiocManager::install("wavClusteR")Bioconductor version 3.8 (BiocManager 1.30.16), R 3.5.1 (2018-07-02)Installing package(s) 'wavClusteR'trying URL 'https://bioconductor.org/packages/3.8/bioc/src/contrib/wavClusteR_2.16.1.tar.gz'Content type 'application/x-gzip' length 728870 bytes (711 KB)==================================================downloaded 711 KBThe downloaded source packages are in        Installation paths not writeable, unable to update packages  path: /apps/R/intel/18.0/3.5.1/lib64/R/library

My session info is as follows:

> sessionInfo()R version 3.5.1 (2018-07-02)Platform: x86_64-pc-linux-gnu (64-bit)Running under: Red Hat Enterprise LinuxMatrix products: defaultBLAS/LAPACK: /opt/intel/18.0.3/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.solocale: [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  [9] LC_ADDRESS=C               LC_TELEPHONE=C            [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     loaded via a namespace (and not attached):[1] BiocManager_1.30.16 compiler_3.5.1      tools_3.5.1
________________________________

**Comment by FedericoComoglio** [comment]
Thank you. As expected, you are using an outdated version of R (from 2018). To avoid any issue with the `wmtsa` dependency, I strongly recommend upgrading to BioC >= 3.12.

Hope this helps. Feel free to re-open the issue if you encounter any problems after upgrading.

**Comment by jalalsiddiqui** [comment]
I will make the necessary changes and let you know of the results.

Jalal
________________________________
