### ISSUE TITLE
Error when trying to list all subsitutions

### ISSUE THREAD

**Issue by jalalsiddiqui** [FedericoComoglio/wavClusteR#9]
I was able to finally install the program.  However when I try to enter the following code on my bam file:

_countTable <- getAllSub( Bam, minCov = 10 )_

I get the following errors.  
_Loading required package: doMC
Considering substitutions, n = 1835248, processing in 1836 chunks_
_...
Error in { : 
  task 1 failed - "In range 49: at least two out of 'start', 'end', and 'width', must
  be supplied."
In addition: Warning message:
executing %dopar% sequentially: no parallel backend registered_

**Comment by FedericoComoglio** [comment]
Also related to #10. Closing.
